defaults:
- agent: ppo
- playground: TensegrityQuadrupedWalk
- _self_
hydra:
  verbose: false
  output_subdir: null
  run:
    dir: .
  job_logging:
    root:
      level: WARNING
checkpointing: true
checkpoint_directory: /media/di/4441-E469/tensaur-main/logs/ind_debug001/slope
export_video: true
render_every: 1
render_camera: track
wandb: false
wandb_project: learning
wandb_entity: tensegrity
tensorboard: true
progress_bar: false
verbose: true
agent:
  num_timesteps: 100000
  num_envs: 512
  num_eval_envs: 1
  episode_length: 1000
  num_evals: 1
  num_minibatches: 32
  num_updates_per_batch: 4
  num_resets_per_eval: 1
  unroll_length: 20
  batch_size: 256
  seed: 1
  log_training_metrics: true
  training_metrics_steps: 1
  reward_scaling: 1.0
  normalize_observations: true
  action_repeat: 1
  discounting: 0.97
  learning_rate: 3e-4
  entropy_cost: 0.01
  max_grad_norm: 1.0
  clipping_epsilon: 0.2
  network_factory:
    policy_hidden_layer_sizes:
    - 512
    - 256
    - 128
    value_hidden_layer_sizes:
    - 512
    - 256
    - 128
    policy_obs_key: state
    value_obs_key: privileged_state
playground:
  xml: /media/di/4441-E469/tensaur-main/src/tensegrity_playground/envs/tensaur/xmls/tensegrity_debug001.xml
  reward_config:
    scales:
      success: 20.0
      reach: 120.0
      action: -0.001
    goal:
      use_goal: true
      tolerance: 0.08
