defaults:
  - agent: ppo
  - playground: TensegrityQuadrupedWalk
  - _self_

# Suppress auto export
hydra:  
  verbose: false
  output_subdir: null  
  run:  
    dir: .
  job_logging:
    root:
      level: WARNING  # Set this to ERROR to reduce even more logs

# Checkpointing
checkpointing: true
checkpoint_directory: /media/di/4441-E469/gait_turn
export_video: true
render_every: 1
render_camera: "track"

# Experiment logging
wandb: false
wandb_project: learning
wandb_entity: tensegrity
tensorboard: true
progress_bar: false
verbose: true